[build]
publish = "public"
command = "make prepare && hugo --source demo --baseURL https://theqajedi.in/"

[context.production.environment]
HUGO_VERSION = "0.75.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1.environment]
HUGO_VERSION = "0.75.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "make prepare && hugo --source demo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.75.1"

[context.branch-deploy.environment]
HUGO_VERSION = "0.75.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"